# Generated by Django 3.2.20 on 2023-09-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.RemoveField(
            model_name='businessowner',
            name='accommodation',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='tenant',
        ),
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_catering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_free_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='square_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
        migrations.DeleteModel(
            name='BusinessOwner',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Tenancy',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
